name: 'Prepare'
description: 'Look in cache for node_modules based on package-lock.json. If cache is empty, install dependencies and make new cache'

runs:
  using: 'composite'
  steps:
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install dependencies
      run: npm install
      shell: bash
